# Generated by Django 4.1.4 on 2023-01-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('new', 'new'), ('converted', 'converted'), ('unconverted', 'unconverted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
